[profile.default]
src = "src"
out = "out"
solc = '0.8.26'
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./out" },
    { access = "read-write", path = "./deployments" },
]

[profile.deploy]
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
tab_width = 4
func_attrs_with_params_multiline = true
ignore = ["lib/**"]
